[package]
name = "qtum_hashes"
version = "0.13.0-qtum"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>", "The Qtum developers"]
license = "CC0-1.0"
repository = "https://github.com/qtumproject/rust-qtum/hashes/"
documentation = "https://docs.rs/bitcoin_hashes/"
description = "Hash functions used by the rust-bitcoin eccosystem"
categories = ["algorithms"]
keywords = [ "crypto", "bitcoin", "qtum", "hash", "digest" ]
readme = "README.md"
edition = "2021"
rust-version = "1.56.1"
exclude = ["tests", "contrib"]
autotests = false

[features]
default = ["std"]
std = ["alloc", "hex/std", "bitcoin-io/std"]
alloc = ["hex/alloc"]
serde-std = ["serde/std"]
# If you want I/O you must enable either "std" or "io".
io = ["bitcoin-io"]
# Smaller (but slower) implementation of sha256, sha512 and ripemd160
small-hash = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
hex = { package = "hex-conservative", version = "0.1.1", default-features = false }

bitcoin-io = { path = "../io",  version = "0.1", default-features = false, optional = true }
schemars = { version = "0.8.3", default-features = false, optional = true }
# Only enable this if you explicitly do not want to use "std", otherwise enable "serde-std".
serde = { version = "1.0", default-features = false, optional = true }

[dev-dependencies]
serde_test = "1.0"
serde_json = "1.0"
